CONNECTION_URL=jdbc:mysql://localhost:3306/scuola_lingue?serverTimezone=UTC&noAccessToProcedureBodies=TRUE
LOGIN_USER=login
LOGIN_PASSWORD=login
AMMINISTRATORE_USER=amministratore
AMMINISTRATORE_PASSWORD=amministratore
SEGRETERIA_USER=segreteria
SEGRETERIA_PASSWORD=segreteria
INSEGNANTE_USER=insegnante
INSEGNANTE_PASSWORD=insegnante